#!/bin/bash -e

main() {
  if [ -d "$HOME/.dotfiles" ]; then
    read -r -p '~/dotfiles already exists on this system. Are you sure you want to continue? [y/n] ' INPUT
    if [[ ! $INPUT =~ ^[Yy]$ ]]; then
      exit 1
    else
      install
    fi
  fi
}

install() {
  if ! [ -x "$(command -v git)" ]; then
      curl -L https://github.com/nicolaballotta/dotfiles/archive/master.tar.gz -o "/tmp/dotfiles-master.tar.gz"
      tar xzf "/tmp/dotfiles-master.tar.gz"
      mv "/tmp/dotfiles-master" "$HOME/.dotfiles"
  else
    git clone --recursive https://github.com/nicolaballotta/dotfiles.git "$HOME/.dotfiles"
  fi

  if [ -d "$HOME/.dotfiles" ]; then
    cd $HOME/.dotfiles
    make all
  else
    printf '\033[31mERROR:\033[0m dotfiles either not downloaded or not extracted successfully\n' >&2
    exit 1
  fi
}

main
